import Footer from '@/components/Footer';
import Header from '@/components/Header';
import { Oswald } from 'next/font/google'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const oswald = Oswald({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${oswald.className}`}>
     
      {children}
      
      </body>
    </html>
  );
}
